# Generated by Django 2.2 on 2021-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnos', to='Clases.Alumnos'),
        ),
    ]
